name: Create release
run-name: Release a "${{ inputs.release_type }}" from "${{ github.ref_name }}" branch

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Type of release to be created
        type: choice
        required: true
        options:
          - patch
          - minor
          - major

defaults:
  run:
    shell: bash

# Don't remove this line
# Avoid multiples releases running at the same time
# If a release is running, the next one will be queued
# Multiples cannot run at the same time because of the git tag, changelog and release creation
concurrency: release-${{ inputs.environment }}

env:
  STABLE_BRANCH: master
  DEPLOYMENT_NAME: <deployment-name> # Eg.: backend
  HARBOR_PROJECT: <project-name> # Eg.: figital-relacionamento
  HARBOR_SQUAD: <squad-name> # Eg.: atende-mais
  HARBOR_NAMESPACE: <namespace-at-registry> # Eg.: atende-mais
  HARBOR_APPLICATION_NAME: <application-name> # Eg.: atende-mais-backend

jobs:
  deploy_development:
    name: Deploy to Development
    runs-on: self-hosted
    environment:
      name: development
      url: "<environment-url>" # use http:// or https:// before the url
    outputs:
      imageFullName: ${{ steps.build.outputs.imageFullName }}
      imageName: ${{ steps.build.outputs.imageName }}
      version: ${{ steps.build.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - uses: viavarejo-internal/atende-mais-github-actions/check-branch-is-updated@v1

      - name: Get current branch
        id: extract_branch
        uses: viavarejo-internal/atende-mais-github-actions/get-current-branch@v1

      - name: Kustomize Lint
        uses: viavarejo-internal/atende-mais-github-actions/kustomize-lint@v1
        with:
          projectName: ${{ env.HARBOR_APPLICATION_NAME }}
          department: ${{ env.HARBOR_PROJECT }}
          namespace: ${{ env.HARBOR_NAMESPACE }}
          version: ${{ steps.extract_branch.outputs.friendly_branch_name }}-RELEASE-SNAPSHOT
          overlays: "development homolog staging production"

      - name: Build Docker image
        id: build
        uses: viavarejo-internal/atende-mais-github-actions/docker-build@v1
        with:
          projectName: ${{ env.HARBOR_APPLICATION_NAME }}
          department: ${{ env.HARBOR_PROJECT }}
          squad: ${{ env.HARBOR_SQUAD }}
          version: ${{ steps.extract_branch.outputs.friendly_branch_name }}-RELEASE-SNAPSHOT

      - name: Push Docker image
        uses: viavarejo-internal/atende-mais-github-actions/docker-push@v1
        with:
          registryUrl: ${{ secrets.DOCKER_REGISTRY }}
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          imageFullName: ${{ steps.build.outputs.imageFullName }}
          imageName: ${{ steps.build.outputs.imageName }}

      - name: Deploy to AKS
        uses: viavarejo-internal/atende-mais-github-actions/aks-deploy@v1
        with:
          environment: development # Used as path of Kustomize
          k8sNamespace: <k8s-namespace> # Eg.: atende-mais-development
          azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          imageName: ${{ steps.build.outputs.imageName }}
          version: ${{ steps.build.outputs.version }}
          deploymentName: ${{ env.DEPLOYMENT_NAME }}

  deploy_homolog:
    name: Deploy to Homolog
    needs: deploy_development
    runs-on: self-hosted
    environment:
      name: homolog
      url: "<environment-url>" # use http:// or https:// before the url

    steps:
      - uses: actions/checkout@v3

      - uses: viavarejo-internal/atende-mais-github-actions/check-branch-is-updated@v1

      - name: Deploy to AKS
        uses: viavarejo-internal/atende-mais-github-actions/aks-deploy@v1
        with:
          environment: homolog
          k8sNamespace: atende-mais-homolog
          azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          imageName: ${{ needs.deploy_development.outputs.imageName }}
          version: ${{ needs.deploy_development.outputs.version }}
          deploymentName: ${{ env.DEPLOYMENT_NAME }}

  # This job is responsible for creating the pre-release/release
  # Will be triggered an enviroment called "pre-production" to request reviews
  # You can configure the approvers in the "Settings > Environments" tab of the repository
  release:
    name: Release
    needs: deploy_homolog
    uses: viavarejo-internal/atende-mais-workflows/.github/workflows/release-workflow.yml@v1
    secrets: inherit
    with:
      release_type: ${{ inputs.release_type }}

  deploy_production:
    name: Deploy production
    needs:
      - deploy_development
      - release
    runs-on: self-hosted
    environment:
      name: production
      url: "<environment-url>" # use http:// or https:// before the url

    steps:
      - uses: actions/checkout@v3

      - name: Pull image
        uses: viavarejo-internal/atende-mais-github-actions/docker-pull@v1
        with:
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          imageFullName: ${{ needs.deploy_development.outputs.imageFullName }}

      - name: Tag image with created version and push
        uses: viavarejo-internal/atende-mais-github-actions/docker-push@v1
        with:
          registryUrl: ${{ secrets.DOCKER_REGISTRY }}
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          imageFullName: ${{ needs.deploy_development.outputs.imageFullName }}
          imageName: ${{ needs.deploy_development.outputs.imageName }}
          tags: ${{ needs.release.outputs.version }}

      - name: Deploy to AKS
        uses: viavarejo-internal/atende-mais-github-actions/aks-deploy@v1
        with:
          environment: production # Used as path of Kustomize
          k8sNamespace: <k8s-namespace> # Eg.: atende-mais-production
          azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          azureClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          imageName: ${{ needs.deploy_development.outputs.imageName }}
          version: ${{ needs.release.outputs.version }}
          deploymentName: ${{ env.DEPLOYMENT_NAME }}

  merge_branches:
    name: Merge branches
    needs: deploy_production
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Merge to stable branch
        uses: viavarejo-internal/atende-mais-github-actions/create-pull-request@v1
        with:
          sourceBranch: ${{ github.event.repository.default_branch }}
          targetBranch: ${{ env.STABLE_BRANCH }}
          autoMerge: true
          deleteBranchAfterMerge: false
          token: ${{ secrets.ACTIONS_TOKEN }}
          skipCi: false
